// Copyright (c) 2024-2025, Qualcomm Technologies, Inc. All rights reserved.
// SPDX-License-Identifier: CC-BY-4.0
[appendix]
[[commentary]]
== Commentary

This section seeks to answer some common questions about the direction we took
in designing the psABI extension, for clarity and for future reference.

=== Why Have We Not Reused Standard Relocations?

We have where we could, for example for the 32-bit branch-immediate instructions
in Xqcibi, which use `R_RISCV_BRANCH` relocations.

We cannot for the 48-bit instructions (even though it looks like we might be
able to, at first glance), for a few reasons:

* QC.EB-type instructions (such as `qc.e.beqi`) where the PC-relative offset is
laid out in fields that exactly match the standard conditional branch
instruction (i.e. `beq`). Note these instructions have both an `simm` field --
which is sign-extended and compared -- and an `imm` field - which will be added
to the PC to calculate where to branch to. We cannot use `R_RISCV_BRANCH`
relocations to fill in the PC-relative offset (though the bits being written by
the relocation are identical), because the linker relaxation process needs to
know which bytes are part of the relocated instruction, rather than just the
location of the fields it might be updating. Therefore we add a new relocation
for these instructions: `R_RISCV_QC_E_BRANCH`.

* QC.EAI-type instructions (such as `qc.e.li`) where the 32-bit immediate is
laid out in a contiguous field from bits 16-47 of the instruction. We cannot use
`R_RISCV_32` relocations here, because this is a data relocation, and on big
endian systems instructions remain little-endian. Using this relocation would
also cause us the same issues with linker relaxation, as we would not be able to
easily work out the instruction extents. Therefore we add a new relocation for
use with `qc.e.li`: `R_RISCV_QC_E_32`.

=== Why Is There Not A Version of the `R_RISCV_QC_E_CALL_PLT` Relocation Without The PLT?

We see the `qc.e.jal` and `qc.e.j` instructions as the equivalent of `call` and
`tail`, in a single 48-bit instruction. RISC-V originally had two call
relocations, one for via the PLT and a direct version. Some time later it was
understood that the non-PLT version is unnecessary, as linkers are allowed to
omit the PLT entry in certain circumstances (including when static linking) and
just resolve directly to the symbol in question.

We sought to avoid the same pitfalls of the main RISC-V psABI, so defined only a
PLT version of the relocation, which linkers can resolve directly to the
relevant function where appropriate.



[#no_new_code_model]
=== Why Have We Not Defined a New Code Model?

The existing RV32 code models focus on addressing the entire 32-bit address
space -- either using absolute address materialization, or using PC-relative
address materialization (potentially via a GOT).

Embedded systems tend to have lower requirements on the size of their address
spaces and also want to use shorter code sequences for address materialization
within these space constraints.

There are two reasons we have not defined and implemented a code model.

The first reason is it requires a lot of implementation and maintenance across
the toolchain (compilers, linkers, libraries), which we do not believe is
justified at this time, especially as this code model will be harder to use than
the conventional 32-bit models.

The second reason is that there is no clear consensus on what size this smaller
address space should be within the instructions defined in the RV32 or Xqci
specifications.

Here are some relevant address materialization options found within RV32 and
`Xqci`, glossing over that some of these types also have alignment requirements
on their immediates:

** Signed 6-bit absolute (RVC CI-type instructions using `x0`)
** Signed 12-bit absolute (RV32 I-type and S-type instructions using `x0`)
** Signed 18-bit absolute (RV32 I-type and S-type with `c.lui`)
** Signed 20-bit absolute (Xqci `qc.li`)
** Signed 32-bit absolute (Xqci `qc.e.li`)
** Signed 9-bit relative to PC (RVC CB-type)
** Signed 12-bit relative to PC (RVC CJ-type)
** Signed 13-bit relative to PC (RV32 B-type and Xqci QC.EB-type)
** Signed 21-bit relative to PC (RV32 J-type)
** Signed 32-bit relative to PC (Xqci QC.EJ-type)
** Signed 6-bit relative to `gp` (RVC CI-type)
** Signed 12-bit relative to `gp` (RV32 I-type and S-type)
** Signed 26-bit relative to `gp` (Xqci QC.EI-type and QC.ES-type)
** Signed 6-bit relative to `sp` (RVC CI-type)
** Signed 12-bit relative to `sp` (RV32 I-type and S-type)
** Signed 26-bit relative to `sp` (Xqci QC.EI-type and QC.ES-type)
** Signed 10-bit relative to `sp` (RVC `c.addi16sp`)
** Unsigned 10-bit relative to `sp` (RVC `c.addi4spn`)

From this, it is clear there is no consensus over what size of address space
lower than 32-bits would actually be useful enough in general for embedded
projects for support in open source toolchains. Every code model has a
maintenance overhead, so it is not possible or sustainable for open source
toolchains to add a new code model for specific embedded projects.

=== Why Are There No Relocations for the 48-bit Load and Store Instructions?

There are a complex series of reasons behind these relating to code models,
materialization sequences and linker relaxations.

Recall that the `Xqcilo` instructions have the following form, where the address
that is loaded or stored is within 26-bits of the value in register `rs1`:

[,asm]
----
    qc.e.lw rd, simm(rs1)
----

There are several options for using this to materialize an address.

One is to use this to materialize a full 32-bit address, as the existing
Medium Low and Medium Any code models require. There is no instruction to
materialize the remaining 6 bits of the address, so we would need to use `lui`
or `auipc` to load the top bits into `rs1`. All sequences including `lui` or
`auipc` and an Xqcilo load or store are equivalent to a shorter code sequence of
the `lui` or `auipc` followed by a standard load or store, so the sequences
including `Xqcilo` instructions do not make sense.

The reasons for not defining a new code model suitable are described in
<<no_new_code_model>>.

Another option would be to only allow `rs1` to be `x0`, and materialize an
absolute 26-bit signed address. This model of relocation, with specific register
constraints would be new in the psABI. This similarly applies to a GP-relative
address materialization that would require `rs1` to be `gp`. While GP-relative
relocations are not per-se new, any that were defined in the past have been
removed, as they were a binutils linker implementation detail, and since then no
relocations with register-specific constraints have been added.

In order to align with the RVI Base behaviour, we have we have added
pseudo-instructions with the `Xqcilo` load and store mnemonics that take a
symbol expression. These emit the standard materialization sequences for the
equivalent width loads and stores. For example:

[,asm]
----
    # Load Example
    qc.e.lw a0, symbol+addend

    # Expands to:
  .Lpcrel_hi1:
    auipc a0, %pcrel_hi(symbol+addend)
    lw a0, %pcrel_lo(.Lpcrel_hi1)(a0)

    # Store Example
    qc.e.sw a0, symbol+addend, t1

    # Expands to:
  .Lpcrel_hi2:
    auipc t1, %pcrel_hi(symbol+addend)
    sw a0, %pcrel_lo(.Lpcrel_hi2)(t1)
----

=== Assembly Guidelines

The Assembler does not have a configuration option to alter its behaviour based
on using the Medium Low or Medium Any code models (it does have an option to
emit Medium Any Position-Independent Sequences). This means the `lla` and `la`
instructions always emit a PC-relative sequence, using `AUIPC`, even in the
Medium Low code model.

When `Xqcili` is available, and the Medium Low code model is being used, we
suggest using `qc.e.li` instead of `la` or `lla`. The syntax is almost
identical, but it is much easier to relax `qc.e.li` instructions than
PC-relative sequences.

[,asm]
----
    # Avoid
    la  a0, symbol+addend
    lla a0, symbol+addend

    # Prefer
    qc.e.li a0, symbol+addend
----
