// Copyright (c) 2024, Qualcomm Technologies, Inc. All rights reserved.
// SPDX-License-Identifier: CC-BY-4.0
[[intro]]
== Introduction

The RISC-V ELF psABI cite:[riscvelfpsabi] makes specific allocations for non-standard extensions. This document is specifies how Qualcomm is using this non-standard extension space for Qualcomm's non-standard (but public) RISC-V ISA extensions.

Currently, this document includes ABI extensions that cover the following of Qualcomm's non-standard RISC-V ISA extension specifications:

* `Xqci` v0.11.0 cite:[xqcispec], which includes:
** `Xqcia` v0.7.0
** `Xqciac` v0.3.0
** `Xqcibi` v0.2.0
** `Xqcibm` v0.7.0
** `Xqcicli` v0.3.0
** `Xqcicm` v0.2.0
** `Xqcics` v0.2.0
** `Xqcicsr` v0.3.0
** `Xqciint` v0.7.0
** `Xqciio` v0.1.0
** `Xqcilb` v0.2.0
** `Xqcili` v0.2.0
** `Xqcilia` v0.2.0
** `Xqcilo` v0.3.0
** `Xqcilsm` v0.5.0
** `Xqcisim` v0.2.0
** `Xqcisls` v0.2.0
** `Xqcisync` v0.2.0

[NOTE]
[%unbreakable]
====
We have taken a few specific directions for this psABI Extension.

The `Xqci` extension is broadly only defined for the RV32 base ISA, so this ABI is designed for the same. We have not considered 64-bit RISC-V implementations at this time.

Together with the `Xqci` extension designers, we settled on using `e.` to denote 48-bit instructions (you could read this as "extended"), much as the standard ISA uses `c.` to denote 16-bit instructions (read as "compressed"). We follow this through when denoting instruction types which start with _QC.E_, and including "E_" in the relevant vendor relocation names for our 48-bit instructions.

We have made no additions to Dynamic relocations as `Xqci` does not add any new whole-program features, just new instructions.
====
