// Copyright (c) 2024-2025, Qualcomm Technologies, Inc. All rights reserved.
// SPDX-License-Identifier: CC-BY-4.0
[[relaxations]]
=== Additional Linker Relaxation Types

The following linker relaxation types are allowed in this psABI, in addition to those defined in the RISC-V ELF psABI.

All these linker relaxations have an implicit requirement that the base architecture is RV32 (like the rest of this psABI extension). Any specific ISA Extensions required to perform the relaxation are documented with each relaxation. The relocatable object's build attributes (if present) should be used to work out if an extension is present, rather than the link result object's merged build attributes.

NOTE: These relaxations are defined to be applied once, rather than the linker relaxing a sequence or group it has already relaxed.
We do not define a preferential order between relaxations, it is understood that the linker performing relaxation will always choose the smallest of the results for which all the conditions are satisfied. Candidates and results below are annotated with their code size (in bytes).

==== Standard to Extended Function/Tail Call Relaxation

  Target Relocation:: R_RISCV_CALL_PLT, R_RISCV_CALL

  Description:: This relaxation type can relax `AUIPC+JALR` into `QC.E.J` or `QC.E.JAL`

  Conditions::
  - The offset between the relocated location and the target symbol or the PLT stub of the target symbol is within range of ±2GiB; and
  - The `rd` of the `JALR` must be `ra` or `x0`.

  Extensions Required:: `Xqcilb`

  Relaxation:: Instruction sequence associated with `R_RISCV_CALL_PLT` (or `R_RISCV_CALL`) can be rewritten into a single `QC.E.JAL` or `QC.E.J` (depending on the destination register of the `JALR`).

NOTE: Using address of PLT stubs of the target symbol or address target symbol
directly will be resolved by linker according to the visibility of the target
symbol.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    auipc ra, 0      # R_RISCV_CALL_PLT symbol
                     # R_RISCV_RELAX
    jalr  ra, ra, 0
    # 8 bytes
----

Relaxation result:
[,asm]
----
    qc.e.jal 0       # R_RISCV_VENDOR QUALCOMM
                     # R_RISCV_QC_E_CALL_PLT symbol
    # 6 bytes
----
--
+
[%unbreakable]
--
This can also be used for tail calls, where the destination register of `JALR` is `X0`.

Relaxation candidate:
[,asm]
----
    auipc ra, 0      # R_RISCV_CALL_PLT symbol
                     # R_RISCV_RELAX
    jalr  x0, ra, 0
    # 8 bytes
----

Relaxation result:
[,asm]
----
    qc.e.j 0         # R_RISCV_VENDOR QUALCOMM
                     # R_RISCV_QC_E_CALL_PLT symbol
    # 6 bytes
----
--

==== Extended to Standard Function/Tail Call Relaxation

  Target Relocation:: R_RISCV_QC_E_CALL_PLT

  Description:: This relaxation can relax `QC.E.J` or `QC.E.JAL` into `JAL`.

  Condition:: The offset between the relocated location and the target symbol or the PLT stub of the target symbol is within range of ±1MiB.

  Relaxation:: Instruction associated with `R_RISCV_QC_E_CALL_PLT` can be rewritten into a single `JAL` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.jal 0  # R_RISCV_VENDOR QUALCOMM
                # R_RISCV_QC_E_CALL_PLT symbol
                # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    jal ra, 0   # R_RISCV_JAL symbol
    # 4 bytes
----
--
+
[%unbreakable]
--

Relaxation candidate:
[,asm]
----
    qc.e.j 0   # R_RISCV_VENDOR QUALCOMM
               # R_RISCV_QC_E_CALL_PLT symbol
               # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    jal x0, 0  # R_RISCV_JAL symbol
    # 4 bytes
----
--

==== Extended to Compressed Function/Tail Call Relaxation

  Target Relocation:: R_RISCV_QC_E_CALL_PLT

  Description:: This relaxation can relax `QC.E.JAL` or `QC.E.J` into `C.JAL` or `C.J` respectively.

  Condition:: The offset between the relocated location and the target symbol or the PLT stub of the target symbol is within range of ±2KiB.

  Extensions Required:: `Zca`

  Relaxation:: `QC.E.JAL` associated with `R_RISCV_QC_E_CALL_PLT` can be rewritten into a single `C.JAL` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.jal 0  # R_RISCV_VENDOR QUALCOMM
                # R_RISCV_QC_E_CALL_PLT symbol
                # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    c.jal 0     # R_RISCV_RVC_JUMP symbol
    # 2 bytes
----
--
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.j 0    # R_RISCV_VENDOR QUALCOMM
                # R_RISCV_QC_E_CALL_PLT symbol
                # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    c.j 0       # R_RISCV_RVC_JUMP symbol
    # 2 bytes
----
--

==== Extended to Standard Global-pointer Address Relaxation

  Target Relocation:: R_RISCV_QC_E_32

  Description:: This relaxation type can relax a `qc.e.li` instruction for loading the address of a symbol reference into an `addi` instruction.

  Condition:: The offset between the global pointer and the symbol is within range of ±2KiB.

  Relaxation:: Instruction associated with `R_RISCV_QC_E_32` can be replaced with an `ADDI` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.li t1, 0  # R_RISCV_VENDOR QUALCOMM
                   # R_RISCV_QC_E_32 symbol
                   # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    addi t1, gp, <gp-offset-for-symbol>
    # 4 bytes
----
--

==== Extended to Standard Address Relaxation

  Target Relocation:: R_RISCV_QC_E_32

  Description:: This relaxation type can relax a `qc.e.li` instruction for loading the address of a symbol reference into a `qc.li` instruction.

  Condition:: The symbol address is located within `0x0` ~ `0x000fffff` or `0xfff00000` ~ `0xffffffff`.

  Extensions Required:: `Xqcili`
+
NOTE: In this Relaxation, both the candidate instruction and the result instruction are from the same extension, so this can be performed even when architecture attributes are not available.

  Relaxation:: Instruction associated with `R_RISCV_QC_E_32` can be replaced with a `QC.LI` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.li t1, 0  # R_RISCV_VENDOR QUALCOMM
                   # R_RISCV_QC_E_32 symbol
                   # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    qc.li t1, <address-of-symbol>
    # 4 bytes
----
--

NOTE: This relaxation could have used `ADDI` as the destination instruction (which is also 4 bytes), but `QC.LI` is valid everywhere `QC.E.LI` is valid, and has a larger immediate range than `ADDI`, which is why we chose `QC.LI` instead.

==== Extended to Compressed LUI Relaxation

  Target Relocation:: R_RISCV_QC_E_32, R_RISCV_QC_ABS20_U

  Description:: This relaxation type can relax a `qc.e.li` or `qc.li` instruction for loading the address of a symbol reference into a `c.lui`.

  Conditions::
  - The symbol address can be represented with a `C.LUI` instruction; and
  - The destination register is not `x0` or `x2`.

  Extensions Required:: `Zca`

  Relaxation:: Instruction associated with `R_RISCV_QC_E_32` or `R_RISCV_QC_ABS20_U` can be replaced with a `C.LUI` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.li t1, 0  # R_RISCV_VENDOR QUALCOMM
                   # R_RISCV_QC_E_32 symbol
                   # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    c.lui t1, <address-of-symbol>
    # 2 bytes
----
--
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.li t1, 0    # R_RISCV_VENDOR QUALCOMM
                   # R_RISCV_QC_ABS20_U symbol
                   # R_RISCV_RELAX
    # 4 bytes
----

Relaxation result:
[,asm]
----
    c.lui t1, <address-of-symbol>
    # 2 bytes
----
--

==== Extended to Standard LUI Relaxation

  Target Relocation:: R_RISCV_QC_E_32

  Description:: This relaxation type can relax a `qc.e.li` instruction for loading the address of a symbol reference into an `lui`.

  Condition:: The symbol address can be represented with an `LUI` instruction.

  Extensions Required:: `Zca`

  Relaxation:: Instruction associated with `R_RISCV_QC_E_32` can be replaced with a `LUI` instruction.

  Example::
+
[%unbreakable]
--
Relaxation candidate:
[,asm]
----
    qc.e.li t1, 0  # R_RISCV_VENDOR QUALCOMM
                   # R_RISCV_QC_E_32 symbol
                   # R_RISCV_RELAX
    # 6 bytes
----

Relaxation result:
[,asm]
----
    lui t1, %hi(symbol)
    # 4 bytes
----
--
